### ISSUE TITLE
Integrate in docker-compose and document my-pubblic-assets 

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#110]
Sharing my-pubblic-assets in the frontend build is a simpler option for users that integrate a remote bucket to serve custom icons.

Now that we changes YAP to frontend/backend and suggesting using docker compose to start the project, we should integrate in the docker compose the volume, review the README in the my-pubblic-assets and explain a user how to use personal assets in th demo.

**Comment by davyvine** [comment]
I modified the current command in frontend Dockerfile to add the VOLUME instead of in the docker-compose.

Previously we are using wrong directory that's why the command is not working. I just changed it to the correct one and it works.
<img width="829" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/3ee989f8-89ac-4e87-b9b9-a12d57f81f8c">

Also updated the README under my-public-assets and modified the config-test-pictures.json file to use the correct path.

For testing, tried adding more assets under my-public-assets and using it as shown below.

<img width="1331" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/cd0176e9-e1f8-4a70-8e55-4f23c4cb5f07">

**Comment by davyvine** [comment]
Update from latest commit:

1. I tried testing again if icons are loaded properly by cleaning up my environment and Marco's comment about the local assets being wiped off based on my previous commit is true.  I think if I just rebuild w/o wiping the data somewhat persist. That's why I was not able to test properly. 

2. I moved away from Dockerfile and used docker-compose to add the VOLUME instead. I used a separate folder named "my-assets" to avoid removing the local "assets" where the local icons are residing.
![image](https://github.com/adt-apjc/YAP/assets/53292972/e59312d8-22dc-4be2-9e6e-405494908e20)

3. After cleaning and rebuilding the container. Local Icons were loaded properly.
<img width="1701" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/7ca9c0a9-2ca1-4b4a-8c36-1954ed5ecfdd">

4. Loading the configure-test-pictures.json. Icons under "my-public-assets" was loaded successfully. 
![image](https://github.com/adt-apjc/YAP/assets/53292972/caf46b58-9c52-4a81-b793-5e5e9f410cbf)


5. I updated the README and configure-test-pictures.json properly to align with the change
