### ISSUE TITLE
expose action headers to UI

### ISSUE THREAD

**Issue by marumer** [adt-apjc/YAP#91]
Currently we support overwrite the endpoint headers in the actions as JSON but this is not supported in the UI, as we currently support in settings. This will be a corner case for some scenarios and we should consider an effective real estate usage

![image](https://github.com/adt-apjc/YAP/assets/12079368/304cb94c-8ea4-49c3-8414-4d0d7cc2bbbc)

**Comment by davyvine** [comment]
I modified the cnc5.0_first_demo.json config in YAP Zoo to test the "headers" feature. Kindly pull the latest config before testing.

1. I Removed the "CNCAuth" Endpoint (previously named CNC2) which contains the headers 
Content-Type: application/yang-data+json and Authorization: {{token}}

2. Under actions, I modified the two PATCH API objects and replaced the endpoint  with "CNC" instead of using CNCAuth and  I added the "headers" field that will override the "CNC" endpoint initial headers "Content-Type": "application/x-www-form-urlencoded"
![image](https://github.com/adt-apjc/YAP/assets/53292972/6e98b12e-6cfe-4c95-a6ac-9048d2ccd4ef)

3. In the UI you can check the "edit" API action modal to see the headers 
<img width="1700" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/b7805e3d-f55b-4086-bfda-8e4acfd224cc">
<img width="1216" alt="image" src="https://github.com/adt-apjc/YAP/assets/53292972/a919ce26-cddf-4296-ab41-481e972575e4">
